import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Create P5-owned tables aligned with AgriLink.sql canonical schema:
 *   - notifications
 *   - ad_packages           (id INT IDENTITY)
 *   - ad_campaigns          (supplier_id, image_url, link_url, start_date, end_date,
 *                            total_impressions, total_clicks)
 *   - ad_events
 *
 * Differences from AgriLink.sql that we keep intentionally:
 *   - target_provinces: JSONB (was TEXT) — better validation & query support
 *   - ad_packages: + created_at, updated_at (auditing)
 *   - ad_events.event_type: enum (was varchar(10)) — type safety
 *   - reviews.is_hidden / hidden_reason: kept for admin moderation feature
 *
 * Required for production deploy (synchronize=false).
 */
export class CreateP5Tables1748390400000 implements MigrationInterface {
  name = 'CreateP5Tables1748390400000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // ── Enums ─────────────────────────────────────────────────────────────
    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notif_type') THEN
          CREATE TYPE "notif_type" AS ENUM (
            'new_order', 'product_approved', 'product_rejected',
            'price_alert', 'member_request', 'new_message'
          );
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ad_type') THEN
          CREATE TYPE "ad_type" AS ENUM ('banner', 'featured', 'spotlight');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ad_status') THEN
          CREATE TYPE "ad_status" AS ENUM (
            'pending_approval', 'active', 'paused', 'rejected', 'expired'
          );
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ad_event_type') THEN
          CREATE TYPE "ad_event_type" AS ENUM ('impression', 'click');
        END IF;
      END
      $$;
    `);

    // ── notifications ─────────────────────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "notifications" (
        "id"         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        "user_id"    UUID NOT NULL,
        "type"       notif_type NOT NULL,
        "title"      VARCHAR(255) NOT NULL,
        "body"       TEXT NOT NULL DEFAULT '',
        "data"       JSONB,
        "is_read"    BOOLEAN NOT NULL DEFAULT FALSE,
        "read_at"    TIMESTAMPTZ,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT "fk_notif_user"
          FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
      );
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_notif_user_unread"
        ON "notifications" ("user_id", "is_read", "created_at" DESC);
    `);

    // ── ad_packages (INT IDENTITY per SQL doc) ────────────────────────────
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "ad_packages" (
        "id"              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name"            VARCHAR(100) NOT NULL,
        "type"            ad_type NOT NULL,
        "price"           NUMERIC(12,2) NOT NULL,
        "duration_days"   INTEGER NOT NULL,
        "max_impressions" INTEGER,
        "description"     TEXT,
        "is_active"       BOOLEAN NOT NULL DEFAULT TRUE,
        "created_at"      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        "updated_at"      TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `);

    // ── ad_campaigns (matches SQL doc field names) ────────────────────────
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "ad_campaigns" (
        "id"                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        "supplier_id"       UUID NOT NULL,
        "package_id"        INTEGER NOT NULL,
        "title"             VARCHAR(255) NOT NULL,
        "image_url"         TEXT,
        "link_url"          TEXT,
        "target_provinces"  JSONB NOT NULL DEFAULT '[]'::jsonb,
        "status"            ad_status NOT NULL DEFAULT 'pending_approval',
        "approved_by"       UUID,
        "approved_at"       TIMESTAMPTZ,
        "rejection_reason"  TEXT,
        "start_date"        DATE,
        "end_date"          DATE,
        "total_impressions" INTEGER NOT NULL DEFAULT 0,
        "total_clicks"      INTEGER NOT NULL DEFAULT 0,
        "created_at"        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        "updated_at"        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT "fk_campaign_supplier"
          FOREIGN KEY ("supplier_id") REFERENCES "users"("id") ON DELETE CASCADE,
        CONSTRAINT "fk_campaign_package"
          FOREIGN KEY ("package_id") REFERENCES "ad_packages"("id") ON DELETE RESTRICT,
        CONSTRAINT "fk_campaign_approver"
          FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE SET NULL
      );
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_campaign_status_dates"
        ON "ad_campaigns" ("status", "start_date", "end_date");
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_campaign_supplier"
        ON "ad_campaigns" ("supplier_id", "created_at" DESC);
    `);

    // ── ad_events ─────────────────────────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "ad_events" (
        "id"          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        "campaign_id" UUID NOT NULL,
        "event_type"  ad_event_type NOT NULL,
        "user_id"     UUID,
        "ip_address"  VARCHAR(45),
        "user_agent"  TEXT,
        "created_at"  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT "fk_event_campaign"
          FOREIGN KEY ("campaign_id") REFERENCES "ad_campaigns"("id") ON DELETE CASCADE,
        CONSTRAINT "fk_event_user"
          FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL
      );
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_event_campaign_date"
        ON "ad_events" ("campaign_id", "created_at" DESC);
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "ad_events"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "ad_campaigns"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "ad_packages"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "notifications"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "ad_event_type"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "ad_status"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "ad_type"`);
  }
}
